-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th12 14, 2021 lúc 04:05 PM
-- Phiên bản máy phục vụ: 10.4.13-MariaDB
-- Phiên bản PHP: 7.2.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `unitop.vn`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbl_orders`
--

CREATE TABLE `tbl_orders` (
  `Order_id` int(11) NOT NULL,
  `Total` int(11) NOT NULL COMMENT 'Đơn vị Yen',
  `Customer_name` varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `City` varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

--
-- Đang đổ dữ liệu cho bảng `tbl_orders`
--

INSERT INTO `tbl_orders` (`Order_id`, `Total`, `Customer_name`, `City`) VALUES
(1, 200000, 'Phạm Ngọc Kiên Chung', 'Oohashi'),
(2, 320000, 'Phạm Mỹ Linh', 'Oohashi'),
(3, 170000, 'Chu Đình Thành', 'Shimizu'),
(4, 240000, 'Trương Tất Phú', 'Tosu'),
(5, 9000, 'Phạm Anh Tuấn', 'Hakata'),
(6, 110000, 'Nguyễn Thị Tươi', 'Sasabaru'),
(7, 320000, 'Phạm Thị Trang', 'Hakata'),
(8, 200000, 'Phạm Ngọc Anh', 'Sasabaru');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbl_pages`
--

CREATE TABLE `tbl_pages` (
  `id` int(11) NOT NULL,
  `page_title` varchar(500) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `page_content` text COLLATE utf8mb4_vietnamese_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

--
-- Đang đổ dữ liệu cho bảng `tbl_pages`
--

INSERT INTO `tbl_pages` (`id`, `page_title`, `created_at`, `page_content`) VALUES
(1, 'Giới thiệu', '2021-09-12 10:39:12', '<p><strong>[Giới thiệu]</strong> - Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eos doloribus eum reiciendis omnis placeat numquam unde nam natus nobis, ipsum incidunt nisi impedit vel adipisci dignissimos ea voluptas minima laboriosam!</p>\r\n        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Unde iste deserunt sed tempore dignissimos beatae.</p>\r\n        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat mollitia sunt adipisci quibusdam recusandae cum, delectus earum quisquam voluptatum dicta perspiciatis illo placeat cupiditate culpa eligendi! Ut distinctio maxime optio?</p>\r\n        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officia eligendi corporis consectetur odit inventore unde officiis quidem praesentium quasi possimus, doloremque ipsa veniam expedita autem tempora sed quos, accusantium ratione? Dolores quos deserunt autem est placeat reiciendis aut repellat laudantium veniam ad obcaecati minus aspernatur enim quae eaque, optio laborum!</p>\r\n        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officia in eligendi impedit consectetur libero facere nostrum sint id dicta sunt earum velit ab, necessitatibus dolorum assumenda excepturi unde optio accusantium, rem aliquid praesentium blanditiis ad illo. Minus obcaecati a veniam molestias fugit blanditiis maiores quae harum quis adipisci quisquam ad, qui minima iure enim corrupti pariatur vero, quia, eum soluta similique reprehenderit. In, aliquam, ratione quam neque cupiditate quaerat ex excepturi eum cum mollitia dicta debitis dolore sunt suscipit quas quo doloribus eaque, facere at provident. Doloremque, animi similique aut, sequi quos velit voluptatem architecto omnis autem eum sunt modi.</p>'),
(2, 'Liên hệ', '2021-09-12 10:39:12', '<p><strong>[Liên hệ]</strong> - Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eos doloribus eum reiciendis omnis placeat numquam unde nam natus nobis, ipsum incidunt nisi impedit vel adipisci dignissimos ea voluptas minima laboriosam!</p>\r\n        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Unde iste deserunt sed tempore dignissimos beatae.</p>\r\n        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat mollitia sunt adipisci quibusdam recusandae cum, delectus earum quisquam voluptatum dicta perspiciatis illo placeat cupiditate culpa eligendi! Ut distinctio maxime optio?</p>\r\n        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officia eligendi corporis consectetur odit inventore unde officiis quidem praesentium quasi possimus, doloremque ipsa veniam expedita autem tempora sed quos, accusantium ratione? Dolores quos deserunt autem est placeat reiciendis aut repellat laudantium veniam ad obcaecati minus aspernatur enim quae eaque, optio laborum!</p>\r\n        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officia in eligendi impedit consectetur libero facere nostrum sint id dicta sunt earum velit ab, necessitatibus dolorum assumenda excepturi unde optio accusantium, rem aliquid praesentium blanditiis ad illo. Minus obcaecati a veniam molestias fugit blanditiis maiores quae harum quis adipisci quisquam ad, qui minima iure enim corrupti pariatur vero, quia, eum soluta similique reprehenderit. In, aliquam, ratione quam neque cupiditate quaerat ex excepturi eum cum mollitia dicta debitis dolore sunt suscipit quas quo doloribus eaque, facere at provident. Doloremque, animi similique aut, sequi quos velit voluptatem architecto omnis autem eum sunt modi.</p>');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbl_products`
--

CREATE TABLE `tbl_products` (
  `id` int(11) NOT NULL,
  `product_title` varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `price` int(11) NOT NULL,
  `code` varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `product_desc` text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `product_thumb` varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `product_content` text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `cat_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

--
-- Đang đổ dữ liệu cho bảng `tbl_products`
--

INSERT INTO `tbl_products` (`id`, `product_title`, `price`, `code`, `product_desc`, `product_thumb`, `product_content`, `cat_id`) VALUES
(1, 'Điện thoại iPhone 12 64GB', 22990000, 'UNI#1', 'Cùng chào đón iPhone 12 64 GB, chiếc điện thoại được ra mắt với nhiều sự nâng cấp. Từ thiết kế sang chảnh cho đến con chip Apple A14 Bionic mang năng lượng hoạt động mạnh mẽ bên trong đầy hứa hẹn.', 'https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-blue-600x600-600x600.jpg', '<h6>Cùng chào đón iPhone 12 64 GB điện thoại được ra mắt với nhiều sự nâng cấp. Từ thiết kế sang chảnh cho đến con chip Apple A14 Bionic mang năng lượng hoạt động mạnh mẽ bên trong đầy hứa hẹn.</span></h6>\r\n        <p>iPhone 12 khoác lên chiếc áo với 5 màu sắc trang nhã, khung viền nhôm cao cấp và mặt trước được phủ lớp kính Ceramic Shield có độ bền gấp 4 lần các thế hệ</p>\r\n        <p><img alt=\"iPhone 12 64GB | Màn hình được phủ lớp kính Ceramic Shield có độ bền gấp 4 lần\" title=\"iPhone 12 64GB | Màn hình được phủ lớp kính Ceramic Shield có độ bền gấp 4 lần\" src=\"https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-040321-030328.jpg\"></p>\r\n        <p>Vì vậy, cho dù bạn chụp ảnh vào ban ngày hay ban đêm, bạn cũng sẽ nhận được mức độ chi tiết và màu sắc của ảnh tốt nhất mà trước đây không thể có được.\r\n\r\n        Tính năng smart HDR 3 cũng giúp cân bằng các yếu tố trong ảnh và làm nổi bật chi tiết cảnh vật xung quanh. Smart HDR 3 sử dụng công nghệ máy học để nhận dạng cảnh, sau đó điều chỉnh độ sắc nét, màu sắc và cân bằng trắng khi cần thiết.</p>', 1),
(2, 'Điện thoại OPPO A15', 3310000, 'UNI#2', 'Mới đây thì OPPO đã cho ra mắt chiếc điện thoại giá rẻ OPPO A15 sở hữu đầy đủ những tính năng của một chiếc điện thoại thông minh thông thường và có những điểm mạnh riêng, từ kích thước màn hình đến hiệu năng mạnh mẽ.', 'https://cdn.tgdd.vn/Products/Images/42/229885/oppo-a15-black-600x600-1-200x200.jpg', '<h6>Mới đây thì OPPO đã cho ra mắt chiếc điện thoại giá rẻ OPPO A15 sở hữu đầy đủ những tính năng của một chiếc điện thoại thông minh thông thường và có những điểm mạnh riêng, từ kích thước màn hình đến hiệu năng mạnh mẽ.</h6>\r\n        <p>OPPO A15 được thiết kế màn hình lớn 6.52 inch cho người dùng có góc nhìn cực kỳ thoải mái, tiện lợi cho công việc cũng như là các hoạt động giải trí đọc báo, xem phim,… Thiết bị sử dụng tấm nền IPS LCD có độ phân giải HD+ cung cấp gam màu rộng mang lại chất lượng hiển thị chân thực, rõ ràng hơn.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/42/229885/oppo-a15-9.jpg\"></p>\r\n        <p>Mang màu sắc tinh tế\r\n        Với mặt lưng 3D và viền máy được làm mỏng, bo cong duyên dáng chiếc điện thoại trông vừa đẹp mắt vừa tạo cảm giác cầm nắm tốt. Mặc dù, OPPO A15 không có nhiều phiên bản màu sắc để khách hàng lựa chọn, nhưng lại sở hữu hai gam màu đơn giản mà không kém phần thanh lịch.</p>\r\n        <p>Cụm 3 camera sắc nét\r\n        Bộ 3 camera mặt sau nằm gọn trong khung hình vuông, đi kèm đèn flash chiếu sáng với độ phân giải camera chính 13 MP duy trì độ rõ nét của ảnh, ống kính macro 2 MP giúp chụp cận cảnh và ống kính độ sâu 2 MP.</p>', 1),
(3, 'Điện thoại Realme C15', 3980000, 'UNI#3', 'Chào đón sự trở lại của Realme với Realme C15, chiếc điện thoại được nhà sản xuất trang bị nhiều tính năng cải tiến hơn, ưu ái cục pin dung lượng lớn,... cùng mức giá hấp dẫn hứa hẹn sẽ đáp ứng tốt nhu cầu người dùng.', 'https://cdn.tgdd.vn/Products/Images/42/226226/realme-c15-600-600x600.jpg', '<h6>Chào đón sự trở lại của Realme với Realme C15, chiếc điện thoại được nhà sản xuất trang bị nhiều tính năng cải tiến hơn, ưu ái cục pin dung lượng lớn,... cùng mức giá hấp dẫn hứa hẹn sẽ đáp ứng tốt nhu cầu người dùng.</h6>\r\n        <p>Diện mạo cuốn hút với thiết kế hình học chuyển màu\r\n        Realme C15 sở hữu 2 phiên bản màu sắc vô cùng ấn tượng đó là: Bạc hải âu và xanh hải dương được lấy cảm hứng từ bờ biển xanh với những cánh chim bay lượn cùng thiết kế hình học chuyển màu chia mặt lưng của chiếc điện thoại này thành ba góc màu độc đáo mang đến vẻ ngoài bắt mắt, tinh tế.\r\n        </p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/42/226226/realme-c15-190320-090348.jpg\"></p>\r\n        <p>Bộ camera đáng tự hào\r\n        Realme C15 sở hữu dàn camera sau có camera chính 13 MP, camera góc siêu rộng 8 MP 119 độ, ống kính retro 2 MP và B&W 2 MP.</p>\r\n        <p>Cùng với ống kính selfie 8 MP, làm đẹp AI và chế độ chân dung mang đến hiệu năng chụp đẹp toàn diện, bắt mắt mọi khoảnh khắc mà bạn đưa máy ảnh lên.\r\n        Được trang bị chip Snapdragon 460 8 nhân khá ổn định không chỉ giúp bạn chơi game trên Realme C15 dễ dàng hơn mà còn tiết kiệm pin hơn. Bên cạnh đó, RAM 4 GB cũng đẩy mạnh phần nào hiệu năng của máy, cho bạn một đa nhiệm mượt mà.\r\n        </p>', 1),
(4, 'Dell Vostro 3590 i7 10510U (GRMGK2)', 18890000, 'UNI#4', 'Laptop Dell Vostro 3590 i7 (GRMGK2) là chiếc laptop được trang bị cấu hình mạnh sử dụng mượt mà ứng dụng văn phòng và đồ họa, học tập. Dell Vostro 3590 laptop lí tưởng cho sinh viên, hay người làm đồ họa kĩ thuật.', 'https://cdn.tgdd.vn/Products/Images/44/220718/dell-vostro-3590-i7-grmgk2-220718-220718-600x600.jpg', '<h6>Laptop Dell Vostro 3590 i7 (GRMGK2) là chiếc laptop được trang bị cấu hình mạnh sử dụng mượt mà ứng dụng văn phòng và đồ họa, học tập. Dell Vostro 3590 laptop lí tưởng cho sinh viên, hay người làm đồ họa kĩ thuật.</h6>\r\n        <p>Hiệu năng ổn định cho sử dụng văn phòng và đồ họa\r\n        Laptop trang bị bộ vi xử lý Intel Core i7 thế hệ thứ 10 tốc độ lên đến 4.9 GHz hiệu năng cao và tiết kiệm điện năng hiệu quả.\r\n        RAM 8 GB đa nhiệm mượt mà, mở khoảng hơn 20 tab Chrome không giật lắc, sử dụng các ứng dụng đồ họa 2D như Photoshop, Ai ổn định.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/44/220718/dell-vostro-3590-i7-grmgk2-kg.jpg\"></p>\r\n        <p>Bàn phím của Dell Vostro 3590 có kích thước tiêu chuẩn, thiết kế hợp lí, độ nảy tốt cho cảm giác gõ êm ái, gõ chính xác.\r\n        Với những tính năng hiện đại cùng hiệu năng mạnh mẽ, Dell Vostro 3590 i7 quả thực là một chiếc laptop đồ họa kĩ thuật đáng sở hữu trong phân khúc.</p>\r\n        <p>Thiết kế gọn gàng, thanh lịch\r\n        Dell Vostro 3590 có thiết kế trẻ trung, lớp vỏ được gia công bền chắc. Kích thước gọn gàng, trọng lượng 1.99 kg và độ dày 19.8 mm, dễ dàng cất gọn vào balo, mang theo hằng ngày.</p>', 2),
(5, 'Dell Vostro 3590 i7 (GRMGK2)', 100000, 'UNI#5', 'Laptop Dell Vostro 3590 i7 (GRMGK2) là chiếc laptop được trang bị cấu hình mạnh sử dụng mượt mà ứng dụng văn phòng và đồ họa, học tập. Dell Vostro 3590 laptop lí tưởng cho sinh viên, hay người làm đồ họa kĩ thuật.', 'https://cdn.tgdd.vn/Products/Images/44/220718/dell-vostro-3590-i7-grmgk2-220718-220718-600x600.jpg', '<h6>Laptop Dell Vostro 3590 i7 (GRMGK2) là chiếc laptop được trang bị cấu hình mạnh sử dụng mượt mà ứng dụng văn phòng và đồ họa, học tập. Dell Vostro 3590 laptop lí tưởng cho sinh viên, hay người làm đồ họa kĩ thuật.</h6>\r\n        <p>Hiệu năng ổn định cho sử dụng văn phòng và đồ họa\r\n        Laptop trang bị bộ vi xử lý Intel Core i7 thế hệ thứ 10 tốc độ lên đến 4.9 GHz hiệu năng cao và tiết kiệm điện năng hiệu quả.\r\n        RAM 8 GB đa nhiệm mượt mà, mở khoảng hơn 20 tab Chrome không giật lắc, sử dụng các ứng dụng đồ họa 2D như Photoshop, Ai ổn định.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/44/220718/dell-vostro-3590-i7-grmgk2-kg.jpg\"></p>\r\n        <p>Bàn phím của Dell Vostro 3590 có kích thước tiêu chuẩn, thiết kế hợp lí, độ nảy tốt cho cảm giác gõ êm ái, gõ chính xác.\r\n        Với những tính năng hiện đại cùng hiệu năng mạnh mẽ, Dell Vostro 3590 i7 quả thực là một chiếc laptop đồ họa kĩ thuật đáng sở hữu trong phân khúc.</p>\r\n        <p>Thiết kế gọn gàng, thanh lịch\r\n        Dell Vostro 3590 có thiết kế trẻ trung, lớp vỏ được gia công bền chắc. Kích thước gọn gàng, trọng lượng 1.99 kg và độ dày 19.8 mm, dễ dàng cất gọn vào balo, mang theo hằng ngày.</p>', 2),
(6, 'HP Envy 13 ba1027TU i5 1135G7 (2K0B1PA)', 20330000, 'UNI#6', 'Máy được trang bị chip xử lý Intel Core i5 gen 11 thế hệ CPU mới nhất của Intel với hiệu suất xử lý và thời lượng pin được cải thiện đáng kể so với thế hệ trước, CPU có 4 lõi và 8 luồng có xung nhịp trung bình là 2.40 GHz', 'https://cdn.tgdd.vn/Products/Images/44/230238/hp-envy-13-ba1027tu-i5-2k0b1pa-103520-093545-600x600.jpg', '<h6>Máy được trang bị chip xử lý Intel Core i5 gen 11 thế hệ CPU mới nhất của Intel với hiệu suất xử lý và thời lượng pin được cải thiện đáng kể so với thế hệ trước, CPU có 4 lõi và 8 luồng có xung nhịp trung bình là 2.40 GHz </h6>\r\n        <p>cho bạn khả năng đa nhiệm tốt, bạn có thể mở cùng lúc nhiều ứng dụng và nhiều tab khác nhau, ví dụ như bạn có thể vừa mở trình duyệt web để nghe nhạc, tra tài liệu vừa có thể mở Word hay Excel để làm việc.\r\n        Laptop HP được trang bị ổ cứng SSD 256 GB cho thời gian mở máy và vào ứng dụng nhanh chóng chỉ tốn vài giây thôi. Dung lượng lưu trữ vừa đủ giúp bạn lưu giữ tốt những tài liệu quan trọng mà không lo lắng ổ cứng sẽ bị đầy nhanh chóng làm giảm hiệu năng của máy.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/44/230238/hp-envy-13-ba1027tu-i5-2k0b1pa-253020-023001.jpg\"></p>\r\n        <p>Tấm nền IPS mang đến góc nhìn rộng bạn có thể nhìn rõ hình ảnh ở mọi góc, loại bỏ tình trạng biến đổi màu và hình dáng của hình ảnh.\r\n\r\n        Công nghệ âm thanh Bang & Olufsen audio cho âm thanh rõ ràng, chân thực mang đến cho bạn những phút giây thư giãn tuyệt vời cùng âm nhạc.</p>\r\n        <p>Laptop HP Envy 13 ba1027TU i5 (2K0B1PA) là sự lựa chọn tuyệt vời dành cho những ai đang tìm kiếm một chiếc laptop mỏng nhẹ lại có hiệu năng ổn định xử lý trơn tru các công việc hằng ngày.</p>', 2),
(7, 'Máy tính bảng Lenovo Tab M10', 4390000, 'UNI#7', 'Tăng cường thêm một sự lựa chọn trong phân khúc máy tính bảng tầm trung, Lenovo Tab M10 sở hữu màn hình kích thước lớn, sắc nét, kết hợp cùng công nghệ âm thanh vòm vượt trội', 'https://cdn.tgdd.vn/Products/Images/522/221928/lenovo-tab-m10-black-600x600.jpg', 'h6>Tăng cường thêm một sự lựa chọn trong phân khúc máy tính bảng tầm trung, Lenovo Tab M10 sở hữu màn hình kích thước lớn, sắc nét, kết hợp cùng công nghệ âm thanh vòm vượt trội, bên cạnh một cấu hình tốt đáp ứng tốt những nhu cầu làm việc và giải trí cơ bản.</h6>\r\n        <p>Màn hình giải trí sắc nét\r\n        Lenovo Tab M10 được trang bị màn hình kích thước lớn 10 inch, độ phân giải HD Pixel trên tấm nền IPS LCD, thể hiện hình ảnh rõ nét ở nhiều góc độ, mang lại cho bạn những phút giây giải trí tuyệt vời.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/522/221928/lenovo-tab-m10-213220-053247.jpg\"></p>\r\n        <p>Máy có thiết kế bo tròn ở các góc tạo cảm giác tinh tế ở mọi góc độ, dễ dàng cấm nắm và sử dụng trong thời gian dài.\r\n\r\n        Mặt lưng thiết bị sử dụng chất liệu nhựa cao cấp với độ bền cao được gia công bằng vật liệu thân thiện với môi trường, không bám mồ hôi và dấu vân tay.</p>\r\n        <p>Các phím bấm được bố trí thuận tiện, dễ dàng thao tác cùng hệ thống loa kép, hỗ trợ âm thanh vòm Dolby Atmos mang tới những trải nghiệm âm thanh sống động và hấp dẫn.\r\n\r\n        Hiệu năng đáp ứng tốt nhu cầu giải trí hàng ngày\r\n        Lenovo Tab M10 được trang bị con chip Snapdragon 429 với 4 nhân tốc độ cao 2.0 GHz đáp ứng tốt nhu cầu như xem phim, lướt web và các tác vụ văn phòng nhẹ.</p>', 3),
(8, 'Máy tính bảng iPad Pro 11 inch Wifi 128GB (2020)', 21990000, 'UNI#8', 'Sau 2 năm, iPad Pro 11 inch 2020 - “Ông vua” của làng máy tính bảng đã quay trở lại. Vẫn thiết kế đó, nhưng mạnh mẽ hơn, cụm camera mới lần đầu xuất hiện.', 'https://cdn.tgdd.vn/Products/Images/522/220163/ipad-pro-11-inch-2020-xam-600x600-600x600.jpg', '<h6>Sau 2 năm, iPad Pro 11 inch 2020 - “Ông vua” của làng máy tính bảng đã quay trở lại. Vẫn thiết kế đó, nhưng mạnh mẽ hơn, cụm camera mới lần đầu xuất hiện. iPad giờ đây không chỉ là chiếc tablet giải trí đơn thuần mà còn trở thành một thiết bị tối ưu cho công việc hay chỉnh sửa đồ họa chuyên sâu.</h6>\r\n        <p>Cụm camera mới tuy “lạ mà quen”\r\n        Apple đã chứng minh vị trí “ngôi vương” máy tính bảng của mình bằng việc trang bị cụm camera hình vuông đặc trưng, khá quen thuộc trên iPhone 11 và bổ sung thêm một cảm biến hoàn toàn mới mang tên LiDAR.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/522/220163/ipad-pro-11-2020-4-9.jpg\"></p>\r\n        <p>Không chạy theo xu hướng số “chấm” khủng như những smartphone mới hiện nay, chỉ với camera góc rộng 12 MP và camera góc siêu rộng 10 MP. iPad Pro đủ khả năng cho ra những tấm ảnh chụp căng nét, chất lượng vượt xa nhiều mẫu điện thoại hay máy tính bảng trên thị trường.</p>\r\n        <p>Ngoài việc chụp hình selfie và gọi video call, giờ đây camera True Depth ở mặt trước của iPad Pro 2020 còn hỗ trợ quay video Full HD, chụp chân dung xóa phông, nhận diện khuôn mặt, cho phép bạn hóa thân thành những nhân vật Animoji vui nhộn khi gọi Facetime cùng bạn bè.</p>', 3),
(9, 'iPad Mini 7.9 inch 64GB (2019) Wifi', 10990000, 'UNI#9', 'Sự trở lại của dòng iPad Mini 7.9 inch Wifi 2019 (iPad Mini 5) đã khiến người dùng bất ngờ bởi suy nghĩ Apple đã khai tử dòng iPad', 'https://cdn.tgdd.vn/Products/Images/522/202706/ipad-mini-79-inch-wifi-2019-gold-200x200.jpg', '<h6>Sự trở lại của dòng iPad Mini 7.9 inch Wifi 2019 (iPad Mini 5) đã khiến người dùng bất ngờ bởi suy nghĩ Apple đã khai tử dòng iPad, tuy nhiên chiếc máy tính bảng này đã trở lại, đẹp và còn mạnh mẽ nhiều hơn xưa.</h6>\r\n        <p>Hiệu năng mạnh mẽ gấp nhiều lần\r\n        Sự nhảy vọt từ phiên bản chip Apple A8 cho đến Apple A12 như các dòng iPhone Xs, Xs Max đã đem lại sự ấn tượng vượt trội cho chiếc iPad Mini này.</p>\r\n        <p><img src=\"https://cdn.tgdd.vn/Products/Images/522/202706/ipad-mini-79-inch-wifi-20199.jpg\"></p>\r\n        <p>Bạn sẽ không ngạc nhiên khi thấy iOS 12 mới nhất của Apple là hệ điều hành đang được sử dụng trên iPad Mini 7.9 inch Wifi 2019.Ngoài ra, iPad Mini 7.9 inch Wifi 2019 cũng sẽ hỗ trợ kết nối được với nhiều phụ kiện, trong đó có, Apple Pencil mang tới nhiều trải nghiệm thú vị hơn trên màn hình như ghi chú, sáng tạo nghệ thuật, viết, vẽ,...\r\n        Thiết kế nhỏ gọn luôn dễ dàng mang theo\r\n        Lý do quan trọng để người dùng chọn iPad Mini bởi thiết kế nhỏ gọn mà máy đẹp lại.</p>\r\n        <p>Màn hình của máy có kích thước lớn cùng độ phân giải cao bạn sẽ có một trải nghiệm làm việc thoải mái.\r\n\r\n        Máy hỗ trợ công nghệ hiển thị True Tone của Apple, giúp ích trong việc hiển thị nội dung và mang lại khả năng điều chỉnh màn hình với các tình huống ánh sáng khác nhau.</p>', 3),
(10, 'iPhone 12 Pro Max', 31990000, 'UNI#11', 'iPhone 12 Pro Max 128 GB một siêu phẩm smartphone đến từ Apple. Máy có một hiệu năng hoàn toàn mạnh mẽ đáp ứng tốt nhiều nhu cầu đến từ người dùng và mang trong mình một thiết kế đầy vuông vức, sang trọng.', 'https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg', '<h6>iPhone 12 Pro Max 128 GB một siêu phẩm đến tu Apple. Máy có một hiệu năng hoàn toàn mạnh mẽ đáp ứng tốt nhiều nhu cầu đến từ người dùng và mang trong mình một thiết kế đầy vuông vức, sang trọng.</h6>\r\n<p>Theo chu kỳ cứ mỗi 3 năm thì iPhone lại thay đổi thiết kế và 2020 là năm đánh dấu cột mốc quan trong này, vì thế rất có thể đây là thời điểm các mẫu iPhone 12 sẽ có một sự thay đổi mạnh mẽ về thiết kế.</p>\r\n<p>iPhone 12 Pro Max sở hữu diện mạo mới mới với khung viền được vát thẳng và mạnh mẽ như trên iPad Pro 2020, chấm dứt hơn 6 năm với kiểu thiết kế bo cong trên iPhone 6 được ra mắt lần đầu tiên vào năm 2014.</p>\r\n<img alt=\"Sự thay đổi về thiết kế vượt trội | iPhone 12 Pro Max\" data-src=\"https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-1.jpg\" class=\" ls-is-cached lazyloaded\" title=\"Sự thay đổi về thiết kế vượt trội | iPhone 12 Pro Max\" src=\"https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-1.jpg\">\r\n<p>Nếu iPad Pro 2020 sử dụng chất liệu nhôm nguyên khối, thì iPhone 12 Pro Max sẽ là chất liệu mặt kính cùng khung viền thép, làm người dùng gợi nhớ nhiều hơn về bộ đôi iPhone 4 /4s huyền thoại với thiết kế đẹp nhất trong lịch sử thiết kế của Apple.</p>', 1),
(11, 'OPPO Reno4 Pro', 24990000, 'UNI#12', 'OPPO chính thức trình làng chiếc smartphone có tên OPPO Reno4 Pro. Máy trang bị cấu hình vô cùng cao cấp với vi xử lý chip Snapdragon 720G, bộ 4 camera đến 48 MP ấn tượng, cùng công nghệ sạc siêu nhanh 65 W nhưng được bán với mức giá vô ưu đãi, dễ tiếp cận.', 'https://cdn.tgdd.vn/Products/Images/42/223497/oppo-reno4-pro-trang-600x600.jpg', '<h6>OPPO chính thức trình làng chiếc smartphone có tên OPPO Reno4 Pro. Máy trang bị cấu hình vô cùng cao cấp với vi xử lý chip Snapdragon 720G, bộ 4 camera đến 48 MP ấn tượng, cùng công nghệ sạc siêu nhanh 65 W nhưng được bán với mức giá vô ưu đãi, dễ tiếp cận.<br>\r\nThiết kế tràn viền siêu ấn tượng</h6>\r\n<p>OPPO Reno4 Pro được trang bị màn hình siêu tràn viền kích thước lớn 6.5 inch, tỉ lệ hiển thị lên tới 93.4%, mật độ điểm ảnh đạt ngưỡng 402 ppi, đạt 100% dải màu DCI-P3 điều này cho phép hình ảnh hiển thị chi tiết, sắc nét và sống động nhất.</p>\r\n<img src=\'https://cdn.tgdd.vn/Products/Images/42/223497/oppo-reno4-pro9.jpg\'>\r\n<p>Bên cạnh đó, màn hình này còn hỗ trợ công nghệ HDR10+, tần số quét 90 Hz vượt trội cùng tốc độ lấy mẫu cảm ứng 180 Hz, mang đến cho người dùng những giây phút thư giãn trải nghiệm các thước phim mãn nhãn hay chơi các tựa game mượt mà, không bị giật lag.\r\n\r\nHơn nữa, màn hình máy được phủ lớp kính bảo vệ cao cấp Gorilla Glass 5, bảo vệ máy một cách tối ưu hơn trong quá trình sử dụng trước những tính huống tác động va đập hay vô tình làm rơi máy. </p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/223497/oppo-reno4-pro11.jpg\">\r\n<p>Bộ 4 camera siêu nét, chống rung ấn tượng\r\nOPPO Reno4 Pro được trang bị bộ 4 camera sau gồm: cảm biến chính siêu nét 48 MP chống rung điện tử EIS, cùng các camera hỗ trợ 8 MP - 2 MP - 2 MP cho bức ảnh lung linh ở nhiều góc chụp như chân dung, góc rộng, zoom và cả khi chụp đêm cũng rất xịn và mịn.</p>', 1),
(12, 'OPPO Reno5 Marvel', 9190000, 'UNI#13', 'OPPO cho ra mắt một phiên bản giới hạn mới OPPO Reno5 Marvel, về hiệu năng cấu hình bên trong máy hoàn toàn tương tự so với Reno5, nhưng về kiểu dáng bên ngoài máy có phần khác biệt với thiết kế tùy chỉnh với mặt lưng có logo Marvel, logo Avengers hoàn toàn mới lạ.', 'https://cdn.tgdd.vn/Products/Images/42/236024/oppo-reno5-marvel-thumb-600x600-600x600.jpg', '<h6>OPPO cho ra mắt một phiên bản giới hạn mới OPPO Reno5 Marvel, về hiệu năng cấu hình bên trong máy hoàn toàn tương tự so với Reno5, nhưng về kiểu dáng bên ngoài máy có phần khác biệt với thiết kế tùy chỉnh với mặt lưng có logo Marvel, logo Avengers hoàn toàn mới lạ.<br>\r\nThiết kế hầm hố, ấn tượng</h6>\r\n<p>Thoạt nhìn, OPPO Reno5 Marvel trông như một chiếc điện thoại chơi game với chủ đạo là màu đen, xen lẫn là các màu đỏ và bạc, sự kết hợp này tạo nên điểm nhấn nổi bật về một chiếc điện thoại mang phong cách thể thao nhưng vẫn toát lên vẻ đẹp thanh lịch</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/236024/oppo-reno5-marvel-4g-001.jpg\">\r\n<p>Giữa mặt lưng là logo Avengers màu bạc nằm trong hình tròn viền đỏ, càng làm lên điểm nhấn cho thiết bị. Vì thế mà bạn không nên mang ốp lưng màu sẽ làm mất đi khí chất ban đầu mà nó mang lại. </p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/236024/oppo-reno5-marvel-7.jpg\">\r\n<p>Không những thế, tần số quét cao 90 Hz sẽ làm mọi thao tác vuốt chạm của bạn trở nên mượt mà hơn, tốc độ cảm ứng 180 Hz giúp bạn trải nghiệm chơi game đồ họa đỉnh cao với độ trễ cực thấp.\r\n<br>\r\nHơn thế nữa, màn hình trên OPPO Reno 5 phiên bản Marvel còn đạt chứng chỉ SGS giảm lượng ánh sáng xanh có hại cho mắt, bảo vệ sức khỏe người dùng khi sử dụng máy trong thời gian dài.</p>', 1),
(13, 'Vivo V20', 7790000, 'UNI#14', 'Vivo V20 là mẫu smartphone đầy năng động cho giới trẻ khi có thiết kế siêu mỏng, phù hợp với xu hướng hiện đại với nhiều màu sắc thời thượng, cấu hình vượt trội cùng hệ thống camera siêu ấn tượng chắc chắn sẽ mang đến cho bạn những trải nghiệm chụp ảnh tuyệt vời.', 'https://cdn.tgdd.vn/Products/Images/42/228453/vivo-v20-600-xanh-hong-2-600x600.jpg', '<h6>Vivo V20 là mẫu smartphone đầy năng động cho giới trẻ khi có thiết kế siêu mỏng, phù hợp với xu hướng hiện đại với nhiều màu sắc thời thượng, cấu hình vượt trội cùng hệ thống camera siêu ấn tượng chắc chắn sẽ mang đến cho bạn những trải nghiệm chụp ảnh tuyệt vời.<br>\r\nThiết kế thời trang, tràn viền</h6>\r\n<p>Vivo V20 có thiết kế hiện đại theo xu hướng của những smartphone cao cấp hiện nay với thiết kế nguyên khối kết hợp cùng mặt lưng kính cao cấp tạo nên độ bóng bẩy, ấn tượng ngay từ cái nhìn đầu tiên.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/228453/vivo-v20-201620-101626.jpg\">\r\n<p>Hơn thế nữa, các chi tiết máy được hoàn thiện tỉ mỉ đến từng chi tiết, cạnh viền được bo tròn nhẹ nhàng để tạo nên tổng thể mềm mại, vừa cho vẻ đẹp sang trọng, lại vừa cho cảm giác cầm nắm mượt mà và không bám dấu vân tay.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/228453/vivo-v20-201320-101356.jpg\">\r\n<p>Mặt lưng của Vivo V20 cũng ấn tượng khi được khoác trên mình hiệu ứng chuyển màu gradient nhẹ nhàng, vô cùng đẹp mắt.\r\n<br>\r\n<b>Màn hình hiển thị sắc nét</b>\r\n<br>\r\nVivo V20 được trang bị một màn hình AMOLED lớn 6.44 inch hỗ trợ HDR10, độ phân giải Full HD+ (1080 x 2400 pixels) sắc nét, kiểu giọt nước, qua đó cắt giảm đáng kể viền bezel đáng kể so với người tiền nhiệm, tăng tỷ lệ hiển thị ở mặt trước.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/228453/vivo-v20-201420-101401.jpg\">\r\n<p>Nổi bật trong số đó chính là chế độ siêu chụp đêm siêu ấn tượng với hàng loạt cảm biến camera chất lượng cùng công nghệ AI tăng cường độ sáng và hiển thị dải màu hoàn hảo giúp bạn có thể chụp những cảnh đẹp lung linh trong đêm tối. \r\n\r\nGiờ đây bạn có thể tha hồ “sống ảo” trong những quán café hay đứng bên con sông đầy thơ mộng giữa trời đêm, Vivo V20 sẽ lưu giữ những khoảnh khắc đẹp nhất của bạn.</p>', 1),
(14, 'Nokia 8000 4G', 1490000, 'UNI#15', 'Bên cạnh Nokia 6300 4G HMD Global đã cho ra mắt chiếc điện thoại Nokia 8000 4G với diện mạo bóng loáng, khá sang trọng trong tầm giá phổ thông hấp dẫn. ', 'https://cdn.tgdd.vn/Products/Images/42/230812/nokia-8000-den-new-600x600-600x600.jpg', '<h6>Bên cạnh Nokia 6300 4G HMD Global đã cho ra mắt chiếc điện thoại Nokia 8000 4G với diện mạo bóng loáng, khá sang trọng trong tầm giá phổ thông hấp dẫn. <br><br>\r\nĐiểm nhấn phong cách</h6>\r\n<p>Chiếc điện thoại có khung và mặt lưng được làm từ nhựa với lớp vỏ sáng bóng như thủy tinh cao cấp và các màu sắc lấy cảm hứng từ đá quý, Nokia 8000 4G được thiết kế để tỏa sáng. Lớp hoàn thiện khung giữa mạ chrome sang trọng hoàn thiện vẻ ngoài.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/230812/nokia-8000-4g-252520-102507.jpg\">\r\n<p>Thiết kế mặt sau Nokia 8000 4G đẹp mắt với một camera và đèn flash nằm phía trên có công dụng như đèn pin.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/230812/nokia-8000-4g-254020-104004.jpg\">\r\n<p>Máy sử dụng màn hình TFT LCD với độ phân giải 240 x 320 pixels và rộng 2.8 inch giúp các cuộc trò chuyện hay sử dụng các chương trình ứng dụng thêm phần rõ ràng hơn.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/230812/nokia-8000-4g-252520-102558.jpg\">\r\n<p>Kết nối 4G trên một chiếc điện thoại giá rẻ\r\nTuy là một thiết bị phổ thông nhưng máy vẫn được trang bị 4G, giờ đây người dùng có thể tham gia các hoạt động giải trí như lướt web, đọc báo, youtube và lên mạng xã hội hay sử dụng google map để tìm đường.</p>', 1),
(15, 'Nokia C20', 1990000, 'UNI#16', '', 'https://cdn.tgdd.vn/Products/Images/42/236437/nokia-c20-blue-1-600x600.jpg', '<h6>Nokia C20 sở hữu thiết kế và cấu hình được tối giản nhưng vẫn có đầy đủ tính năng giải trí đa phương tiện của smartphone thông thường. Với một mức giá siêu hấp dẫn là người dùng phổ thông đã có trong tay mẫu điện thoại giá rẻ đến từ Nokia. </h6>\r\n<p>Nokia C20 được hoàn thiện từ chất liệu vỏ polycarbonate cứng cáp mang đến độ bền cao, bạn sẽ yên tâm hơn khi sử dụng hay mang đi trong mọi hoạt động hằng ngày.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/236437/nokia-c20-002.jpg\">\r\n<p>Hoạt động với vi xử lý 8 nhân và RAM 2 GB, được tối ưu bởi phiên bản Android Go dành riêng cho những dòng máy giá rẻ, mang đến sự mượt mà ngoài mong đợi, các tác vụ cơ bản được xử lý khá ổn định và trơn tru.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/236437/a10.jpg\">\r\n<p>Android 11 (phiên bản Go Edition) được hỗ trợ cập nhật các bản bảo mật hàng tháng trong vòng 2 năm, bảo vệ dữ liệu, sự riêng tư của bạn tốt hơn trước những nguy cơ tiềm ẩn.\r\n<>br\r\nTrải nghiệm tuyệt hơn nhờ màn hình siêu lớn\r\n<br>\r\nThoả sức giải trí với màn hình siêu lớn 6.5 inch của Nokia C20 mang đến chất lượng hiển thị đạt chuẩn HD+, giải trí, chơi game, nghe nhạc hay làm bất kỳ điều gì bạn muốn.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/236437/nokia-c20-009.jpg\">\r\n<p>Tóm lại, với những tính năng cơ bản nhất, Nokia C20 là mẫu điện thoại có mức giá tốt dễ dàng tiếp cận đến nhiều đối tượng người dùng đặc biệt là những ai yêu thích sự bền bỉ và ổn định đến từ thương hiệu điện thoại lâu đời, đáng tin cậy như Nokia.</p>', 1),
(16, 'Vsmart Aris Pro', 5490000, 'UNI#17', 'Thương hiệu smartphone Việt - Vsmart chính thức trình làng Vsmart Aris Pro. Mẫu điện thoại này đánh dấu một bước ngoặc lớn trong làng smartphone với công nghệ camera ẩn trong màn hình, mức giá hợp lý giúp người Việt có cơ hội tiếp cận những công nghệ mới nhất.', 'https://cdn.tgdd.vn/Products/Images/42/228531/vsmart-aris-pro-green-600jpg-600x600.jpg', '<h6>Thương hiệu smartphone Việt - Vsmart chính thức trình làng Vsmart Aris Pro. Mẫu điện thoại này đánh dấu một bước ngoặc lớn trong làng smartphone với công nghệ camera ẩn trong màn hình, mức giá hợp lý giúp người Việt có cơ hội tiếp cận những công nghệ mới nhất.</h6>\r\n<p><b>Camera selfie ẩn, đỉnh cao của thiết kế màn hình tràn viền</b><br>\r\nAris Pro là một trong những dòng điện thoại đầu tiên được trang bị camera selfie với công nghệ ẩn sau màn hình độc đáo, tạo nên một màn hình liền mạch, không còn khiếm khuyết “đục lỗ” hay “giọt nước”.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/228531/vsmart-aris-pro-282420-082418.jpg\">\r\n<p>Với ưu điểm mang tính đột phá, camera ẩn sẽ là xu thế công nghệ kế tiếp trên các dòng smartphone trong những năm sắp tới. Vsmart cũng sẽ là hãng điện thoại Việt Nam đầu tiên tiên phong đưa công nghệ này lên smartphone của mình sớm nhất.\r\n\r\nCamera ẩn sau màn hình (Camera Under Display - CUD) xử lý hình ảnh bằng trí tuệ nhân tạo dành riêng cho camera ẩn, giúp phân tích nguồn sáng trên màn hình loại bỏ hiện tượng ảnh mờ, thiếu, nhiễu, màu sắc sai lệch đi qua lớp kính dày, tái tạo các chi tiết, màu sắc để đưa lại chất lượng ảnh về đúng ban đầu.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/228531/vsmart-aris-pro-214220-034235.jpg\">\r\n<p>Hiệu năng mạnh mẽ với mức giá tầm trung\r\nAris Pro cũng là chiếc điện thoại mạnh mẽ nhất của Vsmart ở thời điểm hiện tại (9/2020) khi trang bị vi xử lý Snapdragon 730 kết hợp cùng RAM 8 GB mạnh mẽ cho hiệu năng tiệm cận với dòng cao cấp, với sức mạnh như vậy giúp điện thoại chơi game có đồ họa phức tạp hoàn toàn không thể làm khó được.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/228531/vsmart-aris-pro-214420-034458.jpg\">\r\n<p>Có thể thấy, với điểm sáng là tiên phong trong công nghệ camera ẩn sau màn hình. Vsmart Aris hứa hẹn tạo nên cơn sốt trong giới công nghệ, mở ra một xu hướng mới về màn hình tràn viền không khiếm khuyết trong tương lai không xa.</p>', 1),
(17, 'Itel it2171', 210000, 'UNI#18', 'Itel it2171 là một chiếc điện thoại cơ bản với 2 SIM 2 sóng và thời lượng pin thoải mái cho những chuyến đi xa.', 'https://cdn.tgdd.vn/Products/Images/42/204125/itel-it-2171-xanh-duong-new-600x600-600x600.jpg', '<h6>Itel it2171 là một chiếc điện thoại cơ bản với 2 SIM 2 sóng và thời lượng pin thoải mái cho những chuyến đi xa.</h6>\r\n<p>Thiết kế nhỏ gọn, dễ dàng mang theo.\r\n<br>\r\nChiếc điện thoại cục gạch Itel it2171 sở hữu vẻ ngoài với thiết kế hiện đại, đậm chất cá tính, năng động của giới trẻ.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/204125/itel-it2171-tgdd-1.jpg\">\r\n<p>Được hoàn thiện từ chất liệu nhựa polycarbonate có độ bền cao và sức chịu va đập tốt, ắt hẳn bạn sẽ không cảm thấy lo lắng mỗi khi làm rơi máy.\r\n<br>\r\n<b>Đa tính năng, tiện dụng</b>\r\n<br>\r\nDù có giá bán khá rẻ nhưng máy vẫn đảm bảo tích hợp đầy đủ tính năng cơ bản và tiện ích nhất như đồng hồ, lịch, đèn pin, 2 SIM 2 sóng online...</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/42/204125/itel-it2171-tgdd-6.jpg\">\r\n<p>Bên cạnh đó máy cũng được trang bị camera hỗ trợ chụp ảnh, tất nhiên chất lượng ảnh chỉ ở mức cơ bản nhất, nhưng đáng khen là có tích hợp đèn flash led để trợ sáng khi chụp ảnh ban đêm.\r\n\r\nPin dùng nhiều ngày\r\nMáy sở hữu viên pin cực khủng có dung lượng lên đến 1000 mAh, hứa hẹn sẽ mang lại cho bạn thời gian sử dụng vô cùng bền bỉ và lâu dài suốt 3 - 4 ngày liên tục hoặc lâu hơn tuỳ mức độ sử dụng.</p>\r\n', 1),
(18, 'Dell Gaming G3 15 i7 10750H (P89F002BWH)', 31490000, 'UNI#19', 'Laptop Dell G3 15 i7 (P89F002BWH) thuộc dòng laptop gaming với cấu hình mạnh mẽ, thiết kế trang nhã và rất sang trọng, dễ lựa chọn cho cả người đi đọc, đi làm, là 1 phiên bản tốt để lựa chọn cho cả nhu cầu làm việc, học tập và chơi game giải trí.', 'https://cdn.tgdd.vn/Products/Images/44/244385/dell-g3-15-i7-p89f002bwh-16-600x600.jpg', '<h6>Laptop Dell G3 15 i7 (P89F002BWH) thuộc dòng laptop gaming với cấu hình mạnh mẽ, thiết kế trang nhã và rất sang trọng, dễ lựa chọn cho cả người đi đọc, đi làm, là 1 phiên bản tốt để lựa chọn cho cả nhu cầu làm việc, học tập và chơi game giải trí.</h6>\r\n<p><b>Sang trọng, tinh tế, phong cách trẻ trung, hiện đại</b>\r\n<br>\r\nĐược đưa vào phân khúc laptop gaming, Dell G3 vì thế trang bị vẻ ngoài cũng mang hơi hướng mạnh mẽ, cá tính, nhưng đủ tinh tế và rất sang trọng để người dùng có thể thoải mái mang theo sử dụng ở mọi nơi.\r\n<br>\r\nLớp vỏ nhựa màu trắng hiện đại, các đường vát góc cạnh rất tinh tế, ngoại hình chắc chắn, trọng lượng 2.58 kg, độ dày 30.96 mm không quá nhẹ nhưng cũng không quá khó khăn để mang kèm nó tới văn phòng, lớp học,…</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/244385/dell-g3-15-i7-p89f002bwh-2-1.jpg\">\r\n<p>Laptop Dell trang bị bàn phím với hành trình phím tốt, cụm phím WASD nổi bật, vùng phím số độc lập giúp thao tác soạn thảo và tính toán cực nhanh nhạy, thêm sự hỗ trợ của đèn nền để thao tác phím chuẩn xác cả trong điều kiện thiếu sáng.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/244385/dell-g3-15-i7-p89f002bwh-8-1.jpg\">\r\n<p>Với đầy đủ các kết nối thông dụng: USB 3.2, HDMI, LAN (RJ45), Thunderbolt 3, USB 2.0 và Mini DisplayPort, thật đơn giản để liên kết laptop với các thiết bị khác phục vụ nhu cầu sao lưu, truyền tải dữ liệu, trình chiếu và kết nối mạng có dây,… Bên cạnh đó, laptop sở hữu 2 kết nối không dây chất lượng cao Bluetooth 5.0 và Wi-Fi 6 AX201 đảm bảo đường truyền nhanh và ổn định khi kết nối mạng không dây hay liên kết các thiết bị di động khác với laptop của bạn.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/244385/dell-g3-15-i7-p89f002bwh-5-1.jpg\">\r\n<p>Chất lượng hình ảnh sắc nét trên màn hình chất lượng cao\r\nMàn hình 15.6 inch với độ phân giải đạt chất lượng Full HD (1920 x 1080) cho hình ảnh hiển thị sắc nét trong từng chi tiết và sống động, chân thực qua từng thước phim giải trí.\r\n\r\nMàn hình LED và góc nhìn rộng WVA (Wide Viewing Angle) tạo lợi thế cho các game thủ khi tham chiến, gia tăng sự thoải mái trong tầm nhìn thiết kế khi sử dụng các ứng dụng đồ họa và cũng thỏa mãn hơn khi xem phim giải trí nhờ chất lượng hình ảnh được bảo toàn tốt ở nhiều góc nhìn.</p>', 2),
(19, ' MacBook Pro M1 2020 Space Grey (MYD82SA/A)', 33490000, 'UNI#20', 'Apple Macbook Pro M1 2020 (MYD82SA/A) sở hữu thiết kế sang trọng kế thừa từ các thế hệ trước và bên trong là một cấu hình ấn tượng từ con chip M1 lần đầu tiên xuất hiện trên MacBook Pro, hiệu năng CPU của máy tăng đến 2.8 lần, hiệu năng GPU tăng 5 lần.', 'https://cdn.tgdd.vn/Products/Images/44/231253/apple-macbook-pro-2020-m1-myd82saa-3-600x600.jpg', '<h6>Apple Macbook Pro M1 2020 (MYD82SA/A) sở hữu thiết kế sang trọng kế thừa từ các thế hệ trước và bên trong là một cấu hình ấn tượng từ con chip M1 lần đầu tiên xuất hiện trên MacBook Pro, hiệu năng CPU của máy tăng đến 2.8 lần, hiệu năng GPU tăng 5 lần.<br>\r\nThiết kế mỏng nhẹ, cao cấp</h6>\r\n<p>Vẫn là thiết kế kim loại nguyên khối thường thấy ở các thế hệ trước, phiên bản MacBook Pro luôn mang lại một ngoại hình sang trọng đẳng cấp, mỏng nhẹ chỉ 15.6 mm từ độ dày, trọng lượng 1.4 kg có thể tự tin đồng hành mọi lúc, cùng bạn đến bất cứ đâu mà bạn muốn như đi học, đi chơi, đi công tác,...</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/231253/apple-macbook-pro-2020-m1-myd82saa-2a-1.jpg\">\r\n<p>Bàn phím Magic trên máy được Apple cho là đã khắc phục hầu hết các nhược điểm của bàn phím Cánh bướm trên các thế hệ trước. Với đèn nền và các phím tắt, bạn có thể xử lý công việc một cách thuận tiện hơn, nhanh chóng hơn.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/231253/apple-macbook-pro-2020-m1-myd82saa-6a-1.jpg\">\r\n<p>Apple trang bị cho MacBook Pro 2020 chip bảo mật T2 mã hóa dữ liệu ổ cứng cùng với cảm biến vân tay nhỏ gọn được tích hợp giúp bạn có thể mở máy nhanh chóng, chỉ cần một lần chạm mà không cần mất quá nhiều thời gian nhập mật khẩu rườm rà.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/231253/apple-macbook-pro-2020-m1-myd82saa-8a-1.jpg\">\r\n<p>Apple Macbook Pro M1 2020 (MYD82SA/A) mang trong mình thiết kế sang trọng, tinh tế kết hợp hiệu năng mạnh mẽ, xử lí mọi tác vụ đơn giản hơn, chắc chắn đây sẽ là sản phẩm laptop sang trọng và đẳng cấp đáng cho bạn sở hữu.</p>', 2),
(20, ' HP 15s fq2559TU i5 1135G7 (46M27PA)', 17590000, 'UNI#21', 'Laptop HP 15s fq2559TU i5 (46M27PA) sở hữu ngoại hình thanh lịch và vi xử lý Intel thế hệ 11 hiện đại, kết hợp công nghệ màn hình cao cấp cho hiệu năng ổn định và chất lượng hình ảnh tuyệt vời.', 'https://cdn.tgdd.vn/Products/Images/44/242627/hp-15s-fq2559tu-i5-46m27pa-600x600.jpg', '<h6>Laptop HP 15s fq2559TU i5 (46M27PA) sở hữu ngoại hình thanh lịch và vi xử lý Intel thế hệ 11 hiện đại, kết hợp công nghệ màn hình cao cấp cho hiệu năng ổn định và chất lượng hình ảnh tuyệt vời.<br>\r\nThiết kế tối giản, vỏ nhựa bền nhẹ</h6>\r\n<p>Laptop HP 15s nổi bật với tông màu bạc sáng chủ đạo, viền mỏng hai bên và các góc được bo tròn vừa phải, cho tổng thể mềm mại. Laptop có trọng lượng khá nhẹ 1.592 kg và độ dày thân máy chỉ 18 mm nên bạn sẽ không cần tốn nhiều sức để mang máy tính theo khi đi làm hay di chuyển hằng ngày.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/242627/hp-15s-fq2559tu-i5-46m27pa-2-1.jpg\">\r\n<p>Bàn phím fullsize phối màu đồng bộ mang tính thẩm mỹ và giúp bạn thuận tiện hơn trong các tác vụ tính toán số liệu. Bàn di chuột lệch về bên trái cho không gian đặt tay rộng rãi và hạn chế gõ nhầm khi sử dụng cụm phím số bên phải.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/242627/hp-15s-fq2559tu-i5-46m27pa-4-1.jpg\">\r\n<p>Ổ cứng SSD 512 GB NVMe PCIe giúp tăng tốc khởi động máy chỉ trong 10 - 15 giây, mở các ứng dụng trong vài giây và phản hồi các thao tác phức tạp nhanh đến không ngờ nhờ tốc độ đọc ghi đạt tới 3500 MB/s. Bộ nhớ đủ cho bạn thoải mái lưu trữ tài liệu hay tải về các bộ phim, file âm nhạc, hình ảnh yêu thích.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/242627/hp-15s-fq2559tu-i5-46m27pa-7-1.jpg\">\r\n<p>Nếu bạn là sinh viên hay nhân viên văn phòng đang tìm kiếm một chiếc laptop học tập - văn phòng sở hữu chất lượng hình ảnh tuyệt vời, kết hợp hiệu năng và đa nhiệm mạnh mẽ, đáp ứng hầu hết nhu cầu làm việc và giải trí thì laptop HP 15s fq2559TU i5 sẽ là sự lựa chọn cực kì thích hợp.</p>', 2),
(21, 'HP EliteBook X360 1030 G8 i7 1165G7 (3G1C4PA)', 47290000, 'UNI#22', 'HP EliteBook X360 1030 G8 i7 (3G1C4PA) mang kiểu dáng nhỏ gọn, siêu di động mà vẫn sang trọng, thanh lịch cùng bộ vi xử lý Intel hế hệ 11 tân tiến đáp ứng tốt nhu cầu làm việc và giải trí hoàn hảo dành cho doanh nhân cần một chiếc laptop tiện lợi di chuyển nhiều.', 'https://cdn.tgdd.vn/Products/Images/44/242413/hp-elitebook-x360-1030-g8-i7-3g1c4pa-19-600x600.jpg', '<h6>HP EliteBook X360 1030 G8 i7 (3G1C4PA) mang kiểu dáng nhỏ gọn, siêu di động mà vẫn sang trọng, thanh lịch cùng bộ vi xử lý Intel hế hệ 11 tân tiến đáp ứng tốt nhu cầu làm việc và giải trí hoàn hảo dành cho doanh nhân cần một chiếc laptop tiện lợi di chuyển nhiều.\r\n<br>\r\nHiệu năng vượt trội, đa nhiệm mượt mà mọi tác vụ</h6>\r\n<p>Cấu hình mạnh mẽ nhờ con chip Intel Core i7 Tiger Lake 1165G7 có tốc độ xung nhịp trung bình 2.80 GHz và đạt tối đa Turbo Boost 4.7 GHz, mang đến khả năng tạo nội dung nhanh gấp 2.7 lần, nâng cao hiệu suất làm việc văn phòng lên đến hơn 20%, xử lý tốt từ các tác vụ văn phòng cơ bản cho đến thao tác đồ họa chuyên nghiệp.\r\n\r\nBên cạnh đó còn tích hợp card đồ họa Intel Iris Xe Graphics cho chất lượng hình ảnh sắc nét đáng kinh ngạc khi xem phim, giải trí cũng như giúp người sáng tạo có thể thiết kế và xây dựng những tệp phức tạp và chi tiết một cách ấn tượng, cùng với đó là khả năng xuất tệp 4K nhanh và dễ dàng.\r\n\r\nRAM 16 GB LPDDR4X (On board) tốc độ Bus RAM 4267 MHz đa nhiệm mượt mà cùng lúc nhiều tác vụ văn phòng, thiết kế và lướt web giải trí mà không lo đơ máy, việc chuyển qua lại giữa các cửa sổ cũng được thực hiện một cách trơn tru.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/242413/hp-elitebook-x360-1030-g8-i7-3g1c4pa-3.jpg\">\r\n<p>Ổ cứng SSD 512 GB NVMe PCIe giúp tăng tốc độ khời động máy, truy xuất dữ liệu nhanh chóng và mang đến không gian bộ nhớ đáp ứng tốt nhu cầu lưu trữ cá nhân như các tài liệu, phim ảnh, file âm thanh,...</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/242413/hp-elitebook-x360-1030-g8-i7-3g1c4pa-5.jpg\">\r\n<p>Thiết kế hiện đại, thời thượng cuốn hút mọi ánh nhìn\r\nHP EliteBook được làm từ kim loại nguyên khối màu bạc sang trọng với những đường nét được vát tỉ mỉ và vô cùng gọn nhẹ chỉ mỏng 16.1 mm, nhẹ 1.25 kg thuận lợi cho bạn bỏ vừa vặn túi xách, balo mang đi làm việc khắp nơi, hội họp hay công tác xa.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/242413/hp-elitebook-x360-1030-g8-i7-3g1c4pa-11.jpg\">\r\n<p>Với những công nghệ và tính năng vượt trội ẩn sau vẻ ngoài  là chiếc laptop cao cấp, sang trọng đáp ứng tốt mọi tác vụ hàng ngày thì HP EliteBook X360 1030 G8 i7 (3G1C4PA) xứng đáng là chiếc laptop đáng sở hữu dành cho giới doanh nhân.</p>', 2),
(22, ' Lenovo Yoga Duet 7 13IML05 i5 10210U (82AS007BVN)', 24990000, 'UNI#23', 'Cực kỳ linh hoạt và mạnh mẽ với cấu hình thế hệ 10 mới nhất, màn hình cảm ứng cùng thiết bị mở khoá khuôn mặt thông minh, laptop Lenovo Yoga Duet 7 13IML05 i5 (82AS007BVN) quả là một tuyệt tác của giới công nghệ 2020.\r\n', 'https://cdn.tgdd.vn/Products/Images/44/228638/lenovo-yoga-duet-7-13iml05-i5-82as007bvn-153521-023547-600x600.jpg', '<h6>Cực kỳ linh hoạt và mạnh mẽ với cấu hình thế hệ 10 mới nhất, màn hình cảm ứng cùng thiết bị mở khoá khuôn mặt thông minh, laptop Lenovo Yoga Duet 7 13IML05 i5 (82AS007BVN) quả là một tuyệt tác của giới công nghệ 2020.<br>\r\nNgoại hình mỏng nhẹ, đẹp mắt</h6>\r\n<p>Với trọng lượng 1.1683 kg (bao gồm máy là 0.7988 kg và bàn phím và 0.3695 kg), Yoga Duet 7 đủ nhẹ và linh hoạt để sử dụng ở mọi nơi. \r\n\r\nĐộ dày chỉ 9.19 mm thì bạn có thể dễ dàng cho vào túi xách và mang theo đi bất cứ đâu mà mình muốn.\r\n\r\nChân đế có thể điều chỉnh nhiều góc độ khác nhau giúp việc phác thảo, đánh máy hay xem phim,... đều có trải nghiệm thoải mái nhất. </p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/228638/lenovo-yoga-duet-7-13iml05-i5-82as007bvn-032320-062341.jpg\">\r\n<p>Tuy Lenovo Yoga Duet 7 được xếp vào hàng laptop nhưng điểm đặc biệt cũng chiếc máy tính xách tay này là bàn phím Bluetooth có thể tháo rời, đồng nghĩa với việc khi bạn tháo bàn phím ra thì Yoga Duet 7 trở thành một chiếc máy tính bảng thời thượng.\r\n\r\nVới tính năng mở khoá bằng khuôn mặt thông minh, Lenovo Yoga Duet 7 sẽ giúp bạn tiết kiệm thời gian và công sức khi việc đăng nhập giờ đây chỉ bằng một nụ cười và sẽ tự động đăng xuất khi bạn rời đi. </p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/228638/lenovo-yoga-duet-7-13iml05-i5-82as007bvn-032420-062438.jpg\">\r\n<p>Bạn thậm chí có thể nói chuyện với trợ lý giọng nói kỹ thuật số - Alexa, phía trên màn hình khóa, tuy nhiên hiện nay máy chưa có hỗ trợ tiếng Việt, thay vào đó chỉ có thể điều khiển bằng tiếng Anh.\r\n\r\nHiệu suất ổn định suốt ngày dài \r\nYoga Duet 7 mang đến cho bạn hiệu suất di động nâng cao nhờ có bộ xử lý Intel Core i5 thế hệ thứ 10 và các tính năng tự động điều chỉnh năng lượng để tối giảm thiểu sự hao pin, tăng tuổi thọ pin, không khó để xử lí mượt các tác vụ văn phòng hằng ngày hay thiết kế đồ họa 2D trên Photoshop, Ai, ở mức cơ bản.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/228638/lenovo-yoga-duet-7-13iml05-i5-82as007bvn-032820-062826.jpg\">\r\n<p>Laptop Lenovo Yoga Duet 7 13IML05 i5 (82AS007BVN) sở hữu hàng loạt các tính năng hiện đại như mở khoá bằng khuôn mặt thông minh, cảm ứng đa điểm, bàn phím có thể tách rời,... thì đây đích thị là một trong những chiếc laptop nhỏ gọn cao cấp phù hợp với đối tượng sinh viên, nhân viên văn phòng.</p>', 2),
(23, 'MacBook Air M1 2020 Gold (MGND3SA/A)', 27490000, 'UNI#24', 'Apple vừa cho ra mắt phiên bản MacBook Air M1 2020 (MGND3SA/A) mới cực kì ấn tượng với con chip M1 mới làm tăng hiệu suất CPU nhanh hơn tới 3.5 lần, tuổi thọ pin dài nhất từ ​​trước đến nay trên MacBook Air. \r\n', 'https://cdn.tgdd.vn/Products/Images/44/231246/apple-macbook-air-2020-mgnd3saa-1-600x600.jpg', '<h6>Apple vừa cho ra mắt phiên bản MacBook Air M1 2020 (MGND3SA/A) mới cực kì ấn tượng với con chip M1 mới làm tăng hiệu suất CPU nhanh hơn tới 3.5 lần, tuổi thọ pin dài nhất từ ​​trước đến nay trên MacBook Air. \r\nSang trọng, cơ động và đẳng cấp </h6>\r\n<p>Được chế tác tinh xảo từ kim loại nguyên khối tái chế, Apple đem đến một phiên bản MacBook Air sang trọng, đẳng cấp nhưng vẫn giữ được độ mỏng nhẹ, thân máy chỉ 16.1 mm, trọng lượng 1.29 kg đề cao tính di động, bắt kịp xu hướng hiện nay.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/231246/apple-macbook-air-2020-mgnd3saa-071220-1041530.jpg\">\r\n<p>Vi xử lý M1 - bước tiến mới của MacBook Air\r\nMacBook Air 2020 lần đầu giới thiệu con chip M1 mà Apple thiết kế đặc biệt dành cho MacBook có CPU 8 lõi cùng với Neural Engine 16 lõi đem đến tốc độ CPU nhanh hơn tới 3.5 lần. GPU 7 lõi tăng hiệu suất nhanh hơn tới 5 lần so với thế hệ trước. Các ứng dụng văn phòng, giải trí đến đồ họa, chỉnh sửa hình ảnh lẫn dựng vlog, render video đều không thể làm khó chiếc MacBook thế hệ mới này. </p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/231246/apple-macbook-air-2020-mgnd3saa-280420-100415-1.jpg\">\r\n<p>Bộ xử lý tín hiệu hình ảnh trong chip M1 giúp bạn trông đẹp nhất cho mọi cuộc gọi FaceTime và hội nghị video. Laptop có đến 3 micrô tích hợp đảm bảo chất lượng đàm thoại tốt, ít tạp âm.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/44/231246/apple-macbook-air-2020-mgnd3saa-280420-100405.jpg\">\r\n<p>Thời lượng pin lên đến 18 giờ, nhiều hơn 6 giờ so với các thế hệ MacBook trước đó, bạn thỏa sức sáng tạo không lo gián đoạn, yên tâm mang theo MacBook trong các chuyến đi.\r\n\r\nHệ điều hành macOS được nâng cấp kho ứng dụng lớn nhất từ trước đến nay, trợ giúp bạn trong tất cả các tác vụ học tập, làm việc đến giải trí, đáp ứng tất cả nhu cầu của bạn.\r\n\r\nTham khảo thêm: Danh sách ứng dụng chạy được trên Macbook chip Apple M1.\r\n\r\nMacBook Air M1 2020 (MGND3SA/A) đánh dấu bước tiến mới trong công nghệ của ông lớn Apple với sức mạnh đáng gờm ẩn bên trong thiết kế thanh mảnh, MacBook Air 2020 xứng đáng là chiếc laptop cao cấp - sang trọng đáng sở hữu của năm.</p>', 2),
(24, 'Samsung Galaxy Tab S7 FE', 13990000, 'UNI#30', 'Samsung chính thức trình làng mẫu máy tính bảng có tên Galaxy Tab S7 FE, máy trang bị cấu hình mạnh mẽ, màn hình giải trí siêu lớn và điểm ấn tượng nhất là viên pin siêu khủng được tích hợp bên trong, giúp tăng hiệu suất làm việc nhưng vẫn có tính di động cực cao.', 'https://cdn.tgdd.vn/Products/Images/522/240254/samsung-galaxy-tab-s7-fe-green-600x600.jpg', '<h6>Samsung chính thức trình làng mẫu máy tính bảng có tên Galaxy Tab S7 FE, máy trang bị cấu hình mạnh mẽ, màn hình giải trí siêu lớn và điểm ấn tượng nhất là viên pin siêu khủng được tích hợp bên trong, giúp tăng hiệu suất làm việc nhưng vẫn có tính di động cực cao.\r\nViên pin “khủng long” vượt mốc 10000 mAh</h6>\r\n<p>Galaxy Tab S7 FE sẽ khiến bạn choáng ngợp với dụng lượng pin cực khủng 10090 mAh đảm bảo cho cường độ làm việc, giải trí liên tục trong nhiều giờ liền.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/240254/samsung-galaxy-tab-s7-fan-editon-05.jpg\">\r\n<p>Theo công bố từ Samsung, với dung lượng lớn này giúp cho Galaxy Tab S7 FE có thể dùng lên tới 12 giờ lướt web với mạng LTE và 13 giờ xem video trực tuyến qua wifi.\r\n\r\nBên cạnh đó, thời gian sạc cũng được rút ngắn đáng kể khi máy hỗ trợ sạc nhanh công suất tối đa lên đến 45 W, tuy nhiên để sạc với tốc độ này bạn cần mua củ sạc phù hợp vì sạc kèm theo máy chỉ 15 W.\r\n\r\nChơi hết sức, làm việc hết mình với màn hình siêu lớn\r\nGalaxy Tab S7 FE có một phiên bản màn hình duy nhất với kích thước lớn 12.4 inch, phần viền bao quanh được thu nhỏ, tạo nên không gian rộng rãi, thoải mái cho bạn làm việc hay giải trí.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/240254/samsung-galaxy-tab-s7-fan-editon-03.jpg\">\r\n<p>Màn hình của máy có độ phân giải 1600 x 2560 pixel đảm bảo cho chất lượng hình ảnh sắc nét trên màn hình lớn. Màn hình lớn giúp các nội dung giải trí được hiển thị tối ưu khi cầm máy ở cả chiều ngang hay dọc, cho bạn trải nghiệm chơi game và xem phim tuyệt vời nhất.\r\n\r\nThiết kế cao cấp, tính di động cao\r\nGalaxy Tab S7 FE vẫn sử dụng thiết kế vát thẳng mạnh mẽ ở phần cạnh viền tương tự Galaxy Tab S7. Tuy vậy, cảm giác cầm S7 FE vẫn rất tốt, các góc cạnh đều đã được xử lý mềm mại hơn, để không gây bất kỳ sự khó chịu hay cấn tay khi cầm.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/240254/samsung-galaxy-tab-s7-fan-editon-01.jpg\">\r\n<p>Galaxy Tab S7 FE cũng là chiếc máy tính bảng có độ mỏng ấn tượng 6.3 mm, dù được trang bị viên pin cực khủng. Trọng lượng 608 g nhẹ hơn nhiều so với laptop, thoải mái để bạn mang theo bên mình và xử lý công việc, kiểm tra email ở bất cứ đâu.\r\n\r\nCấu hình mạnh mẽ\r\nCấu hình của Galaxy Tab S7 FE phần nào đã được cắt giảm so với phiên bản tiêu chuẩn, nhưng các tựa game đồ họa cao và ứng dụng văn phòng vẫn không làm khó được mẫu máy này, nhờ trang bị vi xử lý Snapdragon 750G giúp cho máy có tốc độ mở ứng dụng khá nhanh và chơi game 3D mượt mà.</p>', 3),
(25, 'Huawei MatePad T10s (Nền tảng Huawei Mobile Service)', 5140000, 'UNI#31', 'Chiếc máy tính bảng của Huawei, Huawei MatePad T10s cũng đã chính thức được chào sân. Với vi xử lý 8 nhân mở ra một thế giới giải trí mượt mà, sống động từng khoảnh khắc với màn hình cực lớn, hé lộ một chiếc máy tính bảng tốt trong tầm giá mà bất kỳ ai cũng đều yêu thích.', 'https://cdn.tgdd.vn/Products/Images/522/233257/huawei-t10s-600x600-600x600.jpg', '<h6>Chiếc máy tính bảng của Huawei, Huawei MatePad T10s cũng đã chính thức được chào sân. Với vi xử lý 8 nhân mở ra một thế giới giải trí mượt mà, sống động từng khoảnh khắc với màn hình cực lớn, hé lộ một chiếc máy tính bảng tốt trong tầm giá mà bất kỳ ai cũng đều yêu thích.</h6>\r\n<p>Giải trí sống động với màn hình cực lớn\r\nMatePad T10s sở hữu màn hình 10.1 inch tràn đều cân xứng hoàn hảo ở cả 4 cạnh viền. Giúp cho thiết bị có một thiết kế gọn, nhẹ và mỏng hơn, từng giờ phút trải nghiệm là đều là sự thoải mái.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/233257/huawei-matepad-t10s-181121-031133.jpg\">\r\n<p>Sử dụng tấm nền IPS LCD có độ phân giải 1200 x 1920 pixels cho bạn tận hưởng các nội dung giải trí lớn hơn, rõ ràng hơn với độ sắc nét tuyệt vời, nội dung sẽ linh hoạt thay đổi mượt mà theo chiều cầm ngang hay dọc.</p>\r\n<img src=\"https://cdn.tgdd.vn/2021/01/content/huawei-matepad-t10s-20-800x533.jpg\">\r\n<p>Màn hình MatePad T10s đạt chứng nhận bảo vệ mắt TÜV Rheinland giảm lượng ánh sáng xanh có hại, giữ cho đôi mắt của bạn luôn dễ chịu khi sử dụng trong nhiều giờ liền.\r\n\r\nLoa kép Harman Kardon cho chất âm vòm ấn tượng\r\nKhông chỉ có phần nhìn ấn tượng, mà phần nghe trên MatePad T10s cũng được đánh giá cao khi trang bị bộ đôi loa ngoài đối xứng, giả lập hiệu ứng âm thanh vòm 3D Histen 6.1 Sound nâng tầm trải nghiệm mỗi khi chơi game hay xem phim.</p>\r\n<img src=\"https://cdn.tgdd.vn/2021/01/content/huawei-matepad-t10s-1-800x533.jpg\">\r\n<p>Pin 5100 mAh giải trí, làm việc liên tục nhiều giờ liền\r\nMatePad T10s được trang bị viên pin lớn 5100 mAh thoải mái cho bạn giải trí hay làm việc liên tục trong nhiều giờ liền. Ở bất kỳ không gian và thời gian nào, MatePad T10s sẽ luôn sẵn sàng giúp bạn hoàn thành công việc nhanh chóng.</p>', 3);
INSERT INTO `tbl_products` (`id`, `product_title`, `price`, `code`, `product_desc`, `product_thumb`, `product_content`, `cat_id`) VALUES
(26, 'Lenovo Tab M10 - FHD Plus', 5890000, 'UNI#32', 'Từ việc sử dụng các thiết bị điện tử đa dạng của các gia đình hiện nay, Lenovo đã nắm bắt được nhu cầu thiết yếu này và cho ra mắt chiếc máy tính bảng Lenovo Tab M10 - FHD Plus với những tính năng tiện ích ấn tượng, “khoác chiếc áo” của thời đại và có mức giá siêu ưu đãi.', 'https://cdn.tgdd.vn/Products/Images/522/235365/tab-m10-fhd-plus-600-600x600.jpg', '<h6>Từ việc sử dụng các thiết bị điện tử đa dạng của các gia đình hiện nay, Lenovo đã nắm bắt được nhu cầu thiết yếu này và cho ra mắt chiếc máy tính bảng Lenovo Tab M10 - FHD Plus với những tính năng tiện ích ấn tượng, “khoác chiếc áo” của thời đại và có mức giá siêu ưu đãi.</h6>\r\n<p>Máy tính bảng tiện dụng, gọn nhẹ và linh hoạt\r\nLenovo Tab M10 - FHD Plus được bảo vệ hoàn toàn bởi khung kim loại rắn chắc, các cạnh viền hơi vuông, cong uyển chuyển, sáng bóng. Chiếc máy tính bảng sở hữu vẻ ngoài toát lên vẻ hiện đại thời thượng trong thiết kế đơn giản mà đầy thu hút.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/235365/lenovo-tab-m10-fhd-plus-001.jpg\">\r\n<p>Cấu tạo của Tab M10 - FHD Plus hướng đến mọi đối tượng trong gia đình nên vô cùng gọn nhẹ, chỉ dày 8.15 mm và sở hữu trọng lượng chỉ 460 g. Từ trẻ nhỏ đến người cao tuổi đều dễ dàng cầm nắm sử dụng và mang theo đến bất cứ đâu ngay trong balo nhỏ của bạn.</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/235365/a1.jpg\">\r\n<p>An toàn hơn và nhanh chóng mở khóa máy tính bảng bất cứ khi nào bạn cần bằng công nghệ nhận diện khuôn mặt, chỉ một thao tác vô cùng đơn giản, Tab M10 - FHD Plus đã sẵn sàng hoạt động.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/235365/lenovo-tab-m10-fhd-plus-002.jpg\">\r\n<p>Lenovo Tab M10 - FHD Plus tự hào đảm bảo sức khỏe cho đôi mắt người dùng nhờ khả năng loại bỏ ánh sáng xanh được chứng nhận từ tổ chức TÜV Rheinland, hạn chế mỏi mắt khi sử dụng máy lâu.\r\n\r\n</p>', 3),
(27, 'iPad Pro M1 12.9 inch WiFi Cellular 256GB (2021)', 35290000, 'UNI#33', 'Máy tính bảng iPad Pro M1 12.9 inch Wifi Cellular 256GB (2021) trang bị con chip vô cùng mạnh mẽ M1 cùng công nghệ màn hình mới mini-LED được rất nhiều người dùng đón nhận nồng nhiệt và đánh giá rất tốt sản phẩm này đến từ Apple.', 'https://cdn.tgdd.vn/Products/Images/522/238651/ipad-pro-2021-129-inch-silver-600x600.jpg', '<h6>Máy tính bảng iPad Pro M1 12.9 inch Wifi Cellular 256GB (2021) trang bị con chip vô cùng mạnh mẽ M1 cùng công nghệ màn hình mới mini-LED được rất nhiều người dùng đón nhận nồng nhiệt và đánh giá rất tốt sản phẩm này đến từ Apple.</h6>\r\n<p>iPad Pro M1 12.9 inch 2021 sử dụng chip M1 8 nhân, Apple công bố chip M1 có hiệu năng CPU nhanh hơn 50% và GPU nhanh hơn 40%, đồng thời tiết kiệm năng lượng hơn so với người tiền nhiệm. Đây chính là lợi thế cạnh tranh giúp máy đánh bại các dòng máy khác trong cùng phân khúc.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/238651/ipad-pro-m1-12-9-inch-wifi-cellular-256gb-2021-1.jpg\">\r\n<p>Sức mạnh chưa bao giờ là vấn đề với máy khi thiết bị hoàn toàn có thể đáp ứng được nhiều nhu cầu sử dụng khác nhau từ việc giải trí nghe nhạc, xem phim, chơi game cấu hình cao, cho đến kết nối mạng học trực tuyến đều đáp ứng rất tốt.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/238651/ipad-pro-m1-12-9-inch-wifi-cellular-256gb-2021-18.jpg\">\r\n<p>Bên cạnh hỗ trợ Wifi 6, công nghệ 5G tích hợp trên máy chính là thứ khiến người dùng sẵn sàng “móc hầu bao” để rinh chiếc máy về cho riêng mình.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/238651/ipad-pro-m1-129-inch-08.jpg\">\r\n<p>Đặc biệt, màn hình này sử dụng công nghệ mini-LED hoàn toàn mới, gồm 10.000 bóng LED siêu nhỏ cho độ tương phản cao 1.000.000:1 vì thế độ sáng tối đa có thể đạt 1600 nits để người dùng có những phút giây trải nghiệm thị giác tột đỉnh.\r\n\r\n</p>', 3),
(28, 'iPad Air 4 Wifi Cellular 64GB (2020)', 20790000, 'UNI#34', 'Trong sự kiện Time Flies, Apple đã giới thiệu đến người dùng chiếc iPad Air 4 Wifi Cellular 64GB (2020) với thiết kế tương tự iPad Pro, ngoại hình của Air 4 đã được làm mới so với thế hệ iPad Air 3, cấu hình được nâng cấp mạnh mẽ cùng với nhiều cải tiến đáng giá. ', 'https://cdn.tgdd.vn/Products/Images/522/228897/ipad-4-cellular-den-new-600x600-600x600.jpg', '<h6>Trong sự kiện Time Flies, Apple đã giới thiệu đến người dùng chiếc iPad Air 4 Wifi Cellular 64GB (2020) với thiết kế tương tự iPad Pro, ngoại hình của Air 4 đã được làm mới so với thế hệ iPad Air 3, cấu hình được nâng cấp mạnh mẽ cùng với nhiều cải tiến đáng giá. </h6>\r\n<p>iPad Air 4 được trang bị màn hình Liquid Retina kích thước 10.9 inch có độ phân giải 1640 x 2360 Pixels, được tích hợp công nghệ True Tone cùng với dải màu P3 chuẩn điện ảnh sẽ mang lại chất lượng hiển thị cao, màu sắc tự nhiên gần như sát với màu sắc gốc. \r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/228897/ipad-air-4-wifi-cellular-64gb-2020-231320-041336.jpg\">\r\n<p>iPad Air 4 có thiết kế phẳng, mạnh mẽ, 4 góc được bo tròn, viền màn hình cũng đã mỏng đi đáng kể khi so với Air 3. Để viền màn hình được mỏng đều ở 4 cạnh như vậy thì Apple đã loại bỏ phím home ở mặt trước nhằm tiết kiệm diện tích. Theo đó Touch ID cũng đã được thiết kế lại, được đặt lên phím nguồn nằm ở cạnh trên của máy.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/228897/ipad-air-4-wifi-cellular-64gb-2020-231320-041354.jpg\">\r\n<p>iPad Air thế hệ thứ 4 có đến 5 phiên bản màu sắc bao gồm: Xám, Bạc, Vàng hồng, Xanh lá cây và Xanh da trời. Toàn bộ phần khung viền của iPad Air 4 được hoàn thiện 100% từ nhôm tái chế, thân thiện với môi trường.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/228897/ipad-air-4-wifi-cellular-64gb-2020-233320-043332.jpg\">\r\n<p>iPad Air 4 là sản phẩm đầu tiên sử dụng chip Apple A14 Bionic, hiệu năng CPU của chip A14 nhanh hơn đến 40% so với chip A12 Bionic của iPad Air 3. Con số này là 30% khi so sánh hiệu năng về đồ họa (GPU).\r\n\r\n</p>', 3),
(29, 'Masstel Tab 10.1', 3290000, 'UNI#35', 'Masstel Tab 10.1 inch chiếc máy tính bảng có thiết kế gọn nhẹ, màn hình lớn hiển thị rõ nét cùng hiệu năng hoạt động ổn định đem đến cho người dùng sự tiện lợi, mượt mà, xứng đáng là thiết bị học tập, giải trí tuyệt vời cho tất cả mọi người.', 'https://cdn.tgdd.vn/Products/Images/522/234414/masstel-tab-10-den-600x600-600x600.jpg', '<h6>Masstel Tab 10.1 inch chiếc máy tính bảng có thiết kế gọn nhẹ, màn hình lớn hiển thị rõ nét cùng hiệu năng hoạt động ổn định đem đến cho người dùng sự tiện lợi, mượt mà, xứng đáng là thiết bị học tập, giải trí tuyệt vời cho tất cả mọi người.</h6>\r\n<p>Masstel Tab 10.1 inch mang ngôn ngữ thiết kế nguyên khối với chất liệu kim loại sang trọng, kiểu dáng vuông vắn như trên một chiếc máy tính bảng cao cấp.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/250589/masstel-tab-10-1-1.jpg\">\r\n<p>Bốn cạnh viền được làm mỏng và đều nhau mang tới hiệu ứng thị giác tuyệt vời và trọng lượng máy chỉ 510 gram, mang lại sự thuận tiện trong quá trình thao tác, dễ dàng sử dụng và mang theo bên mình.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/250589/masstel-tab-10-1-3.jpg\">\r\n<p>Masstel Tab 10.1 inch được trang bị vi xử lý 8 nhân Spreadtrum SC9863A cho tốc độ xử lý 1.6 GHz, với những tác vụ cơ bản như đọc báo, xem phim, gọi video hay thậm chí một số tựa game nhẹ thì máy vẫn đáp ứng tốt, ổn định.\r\n\r\n</p>\r\n<img src=\"https://cdn.tgdd.vn/Products/Images/522/250589/masstel-tab-10-1-5.jpg\">\r\n<p>Được trang bị công suất sạc 10 W không quá cao nhưng bù lại Masstel Tab 10.1 inch sở hữu dung lượng pin 6000 mAh. Masstel Tab 10.1 inch sẽ mang đến khả năng trải nghiệm liên tục cả ngày, thoải mái sử dụng lướt web, đọc báo xem phim mà không cần lo ngại đến vấn đề hết pin giữa chừng.\r\n\r\n</p>', 3);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbl_product_cats`
--

CREATE TABLE `tbl_product_cats` (
  `id` int(11) NOT NULL,
  `cat_title` varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

--
-- Đang đổ dữ liệu cho bảng `tbl_product_cats`
--

INSERT INTO `tbl_product_cats` (`id`, `cat_title`) VALUES
(1, 'Điện thoại'),
(2, 'Laptop'),
(3, 'Máy tính bảng');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tbl_users`
--

CREATE TABLE `tbl_users` (
  `user_id` int(11) NOT NULL,
  `username` varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `fullname` varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `password` varchar(40) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `age` int(3) NOT NULL,
  `address` varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  `earn` int(11) NOT NULL COMMENT 'Đơn vị Yen',
  `gender` enum('male','female') COLLATE utf8mb4_vietnamese_ci NOT NULL DEFAULT 'male',
  `active_token` varchar(40) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  `is_active` enum('0','1') COLLATE utf8mb4_vietnamese_ci DEFAULT '0',
  `reg_date` int(11) UNSIGNED DEFAULT NULL,
  `reset_pass_token` varchar(40) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  `reset_pass_date` int(11) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

--
-- Đang đổ dữ liệu cho bảng `tbl_users`
--

INSERT INTO `tbl_users` (`user_id`, `username`, `fullname`, `password`, `age`, `address`, `email`, `earn`, `gender`, `active_token`, `is_active`, `reg_date`, `reset_pass_token`, `reset_pass_date`) VALUES
(46, 'chunchun', 'Phạm Ngọc Kiên Chung', '1c0ae1eddd07fb925a7de153d497a138', 0, '', '18bf3166@fc.jue.ac.jp', 0, 'male', 'cd009a1ace0da692b61e20639dd44361', '1', 1633773984, '', 1633799398),
(47, 'phamchung', 'Phạm Ngọc Kiên Chung', '1c0ae1eddd07fb925a7de153d497a138', 0, '', 'phamngockienchung@icloud.com', 0, 'male', '56057d46cc3a0d7f8a52173ca41a4a83', '0', 1633782303, NULL, NULL),
(48, 'lynhpham', 'Phạm Mỹ Lynh', '1779aef9d98a7958f0034a9ef4f8b4eb', 0, '', 'linhph812@gmail.com', 0, 'male', '8006f2fcc62528e25a595fe7a4bcf92b', '1', 1633787366, NULL, NULL);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `tbl_orders`
--
ALTER TABLE `tbl_orders`
  ADD PRIMARY KEY (`Order_id`);

--
-- Chỉ mục cho bảng `tbl_pages`
--
ALTER TABLE `tbl_pages`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `tbl_products`
--
ALTER TABLE `tbl_products`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `tbl_product_cats`
--
ALTER TABLE `tbl_product_cats`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `tbl_users`
--
ALTER TABLE `tbl_users`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `tbl_orders`
--
ALTER TABLE `tbl_orders`
  MODIFY `Order_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT cho bảng `tbl_pages`
--
ALTER TABLE `tbl_pages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT cho bảng `tbl_products`
--
ALTER TABLE `tbl_products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;

--
-- AUTO_INCREMENT cho bảng `tbl_product_cats`
--
ALTER TABLE `tbl_product_cats`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT cho bảng `tbl_users`
--
ALTER TABLE `tbl_users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
